version: "3.9"
services:
  postgres:
    container_name: chessdb
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - 6543:5432

  backend:
    container_name: chessbackend
    image: chess-backend
    ports:
      - 8080:8080

  frontend:
    container_name: chessfrontend
    image: chess-frontend
    ports:
      - 4200:80

volumes:
  pg-data:
